### ISSUE TITLE
Crash righ after /chunkProfiler start in The End

### ISSUE THREAD

**Issue by aburone** [pitbox46/ChunkProfiler#1]
Just ran the command and the game crashed to main menu (notenoughcrashes prevented a crash to desktop)
https://hastebin.com/anaqenabel.rb

One more try
https://hastebin.com/esehudaduk.rb

And another
https://hastebin.com/ififibupoh.rb

**Comment by pitbox46** [comment]
I will be looking into it. I have uploaded a new version to Curseforge which hopefully helps.
